run: plane.o crew.o flight.o planeCol.o crewCol.o flightCol.o HW5Main.o pilot.o copilot.o cabin.o
	g++ plane.cpp crew.cpp flight.cpp planeCol.cpp crewCol.cpp flightCol.cpp HW5Main.cpp pilot.cpp copilot.cpp cabin.cpp -o run
	
plane.o: plane.h plane.cpp
	g++ -c plane.cpp

crew.o: crew.h crew.cpp
	g++ -c crew.cpp

flight.o: flight.h flight.cpp
	g++ -c flight.cpp

planeCol.o: planeCol.h planeCol.cpp
	g++ -c planeCol.cpp

crewCol.o: crewCol.h crewCol.cpp
	g++ -c crewCol.cpp

flightCol.o: flightCol.h flightCol.cpp
	g++ -c flightCol.cpp

HW5Main.o: HW5Main.cpp
	g++ -c HW5Main.cpp

pilot.o: pilot.h pilot.cpp
	g++ -c pilot.cpp
	
copilot.o: copilot.h copilot.cpp
	g++ -c copilot.cpp
	
cabin.o: cabin.h cabin.cpp
	g++ -c cabin.cpp